'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class WebForm1

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''incrct_Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents incrct_Label1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''incrct_Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents incrct_Label2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''incrct_Label3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents incrct_Label3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''incrct_Label4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents incrct_Label4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''incrct_Label5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents incrct_Label5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''incrct_Label6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents incrct_Label6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''incrct_Label7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents incrct_Label7 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''incrct_Label8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents incrct_Label8 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''incrct_Label9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents incrct_Label9 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''crct_Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents crct_Label1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''crct_Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents crct_Label2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''crct_Label3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents crct_Label3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''crct_Label4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents crct_Label4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''crct_Label5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents crct_Label5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''crct_Label6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents crct_Label6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''crct_Label7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents crct_Label7 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''crct_Label8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents crct_Label8 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''crct_Label9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents crct_Label9 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tottime_Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tottime_Label1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tottime_Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tottime_Label2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tottime_Label3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tottime_Label3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tottime_Label4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tottime_Label4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tottime_Label5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tottime_Label5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tottime_Label6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tottime_Label6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tottime_Label7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tottime_Label7 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tottime_Label8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tottime_Label8 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tottime_Label9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tottime_Label9 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''inctime_Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents inctime_Label1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''inctime_Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents inctime_Label2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''inctime_Label3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents inctime_Label3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''inctime_Label4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents inctime_Label4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''inctime_Label5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents inctime_Label5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''inctime_Label6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents inctime_Label6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''inctime_Label7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents inctime_Label7 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''inctime_Label8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents inctime_Label8 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''inctime_Label9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents inctime_Label9 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''crcttime_Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents crcttime_Label1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''crcttime_Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents crcttime_Label2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''crcttime_Label3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents crcttime_Label3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''crcttime_Label4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents crcttime_Label4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''crcttime_Label5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents crcttime_Label5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''crcttime_Label6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents crcttime_Label6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''crcttime_Label7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents crcttime_Label7 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''crcttime_Label8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents crcttime_Label8 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''crcttime_Label9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents crcttime_Label9 As Global.System.Web.UI.WebControls.Label
End Class
